; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.1.3-LPC on Sat Jul 25 2020 21:42:13 GMT+0200 (Central European Summer Time)
; insert codes for deploying the Z probe here
