; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.1.3-LPC on Sat Jul 25 2020 21:42:14 GMT+0200 (Central European Summer Time)

