; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.3-LPC on Sat Jul 25 2020 21:42:15 GMT+0200 (Central European Summer Time)
; Wait for set temperatures to be reached
M116 P0

