; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2 on Mon Jun 10 2019 14:34:08 GMT+0200 (Srednjeevropski poletni čas)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


