; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.1.3-LPC-1 on Thu Aug 13 2020 09:40:16 GMT+0100 (British Summer Time)
; insert codes for retracting the Z probe here

M280 P0 S90