; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.1.3-LPC-1 on Thu Aug 13 2020 09:40:18 GMT+0100 (British Summer Time)

