; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.3-LPC-1 on Thu Aug 13 2020 09:40:18 GMT+0100 (British Summer Time)
; Wait for set temperatures to be reached
M116 P0

