; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Fri May 14 2021 08:18:16 GMT-0600 (Mountain Daylight Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


