; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Fri May 14 2021 08:18:18 GMT-0600 (Mountain Daylight Time)
; Wait for set temperatures to be reached
M116 P0

