; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+6 on Wed Mar 15 2023 21:20:36 GMT+0200 (Eastern European Standard Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


