; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+6 on Wed Mar 15 2023 21:20:38 GMT+0200 (Eastern European Standard Time)

