; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+6 on Wed Mar 15 2023 21:20:39 GMT+0200 (Eastern European Standard Time)
; Wait for set temperatures to be reached
M116 P0

