; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC+11 on Thu May 20 2021 16:25:05 GMT-0600 (Mountain Daylight Time)

