; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC+11 on Thu May 20 2021 16:25:06 GMT-0600 (Mountain Daylight Time)
; Wait for set temperatures to be reached
M116 P0

