; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC+9 on Thu Apr 15 2021 16:59:08 GMT+0200 (Mitteleuropäische Sommerzeit)
M280 P0 S90 ; retract BLTouch

