; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC+9 on Thu Apr 15 2021 16:59:08 GMT+0200 (Mitteleuropäische Sommerzeit)

