; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC on Mon Mar 01 2021 13:22:52 GMT-0500 (Eastern Standard Time)
M280 P0 S90 ; retract BLTouch

