; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC on Mon Mar 01 2021 13:22:52 GMT-0500 (Eastern Standard Time)
; Wait for set temperatures to be reached
M116 P0

