; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC on Tue Mar 02 2021 16:34:41 GMT+0100 (Mitteleuropäische Normalzeit)
M280 P0 S10 ; deploy BLTouch

