; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC on Mon Feb 15 2021 14:41:39 GMT+0100 (Mitteleuropäische Normalzeit)
; M83            ; relative extruder moves
; G1 E-10 F3600  ; retract 10mm of filament
; G91            ; relative positioning
; G1 Z5 F360     ; lift Z by 5mm
; G90            ; absolute positioning
M120

M9       ; run m9.g

; G0 X0 Y220 