; resume.g
; called before a print from SD card is resumed
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC on Mon Feb 15 2021 14:41:39 GMT+0100 (Mitteleuropäische Normalzeit)
; G1 R1 X0 Y0 Z5 F6000 ; go to 5mm above position of the last print move

; M83                  ; relative extruder moves
; G1 E10 F3600         ; extrude 10mm of filament
G1 R1 S0 F12000         ; go back to the last print move

M7			; Run m7.g

G4 S1