; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC on Mon Feb 15 2021 14:41:40 GMT+0100 (Mitteleuropäische Normalzeit)

; M9       ; run m9.g


G28 Y
G28 x