; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC on Tue Mar 02 2021 16:34:42 GMT+0100 (Mitteleuropäische Normalzeit)
; Wait for set temperatures to be reached
M116 P0

