; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Sat Feb 22 2020 23:29:20 GMT-0500 (Eastern Standard Time)
M280 P0 S90 ; retract BLTouch

