; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.1.4 on Thu May 07 2020 07:31:54 GMT+0200 (Mitteleuropäische Sommerzeit)
; Wait for set temperatures to be reached
M116 P0

