; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.3.0-LPC-STM32+01 on Tue Jul 27 2021 16:34:11 GMT-0600 (Mountain Daylight Time)
M280 P0 S10 ; deploy BLTouch

