; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.0-LPC-STM32+01 on Tue Jul 27 2021 16:34:12 GMT-0600 (Mountain Daylight Time)

