; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.0-LPC-STM32+01 on Tue Jul 27 2021 16:34:12 GMT-0600 (Mountain Daylight Time)
; Wait for set temperatures to be reached
M116 P0

