; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+4 on Tue Sep 06 2022 09:00:28 GMT-0600 (Mountain Daylight Time)

