; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC+10 on Mon Apr 26 2021 16:39:38 GMT+0200 (Mitteleuropäische Sommerzeit)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


