; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC+10 on Mon Apr 26 2021 16:39:39 GMT+0200 (Mitteleuropäische Sommerzeit)
M280 P0 S10 ; deploy BLTouch

