; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.1-LPC-STM32+5 on Sun Jan 23 2022 16:44:36 GMT-0700 (Mountain Standard Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


