; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2 on Mon Jun 10 2019 14:34:08 GMT+0200 (Srednjeevropski poletni čas)

M300 S2210 P250