; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2 on Thu Jan 09 2020 20:33:59 GMT+0000 (Greenwich Mean Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


