; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2 on Thu Jan 09 2020 20:34:01 GMT+0000 (Greenwich Mean Time)
; Wait for set temperatures to be reached
M116 P0

