; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+6 on Sat Apr 01 2023 19:37:05 GMT-0600 (Mountain Daylight Time)
; Wait for set temperatures to be reached
M116 P0

