; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC+9 on Fri Apr 16 2021 16:56:46 GMT+0100 (British Summer Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


