; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC+9 on Fri Apr 16 2021 16:56:47 GMT+0100 (British Summer Time)

M118 P2 S"//action::paused" ; allow screen to know the job has been paused

G91 			; relative movement
G1 Z2 E-6 F3600 ; retract 6mm and raise 2mm
G90 			; absolute movement
G28 X U 		; home all tools axes