; resume.g
; called before a print from SD card is resumed
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC+9 on Fri Apr 16 2021 16:56:47 GMT+0100 (British Summer Time)
T R1 					; select tool last used
G1 R1 X0 Y0 Z2 F5000 	; move to 2mm above the resume location
G1 R1 Z0 F500 	; move to the Z resume location
G1 E6 F3600 		; detract