; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC+9 on Fri Apr 16 2021 16:56:47 GMT+0100 (British Summer Time)


M118 P2 S"//action:cancel"   ; Allow the screen to know when a job has stopped.

M0 ; to allow stop.g to be ran.

