; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.1.4-LPC-5 on Fri Sep 25 2020 18:47:31 GMT+0200 (Mitteleuropäische Sommerzeit)

