; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+4 on Thu Oct 13 2022 14:11:35 GMT-0600 (Mountain Daylight Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


