; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+4 on Thu Oct 13 2022 14:11:37 GMT-0600 (Mountain Daylight Time)
; Wait for set temperatures to be reached
M116 P0

